### ISSUE TITLE
Installation, execution.

### ISSUE THREAD

**Issue by jpmfc6** [LiamWilbraham/smilescombine#1]
I'm not sure the installation instructions are sufficient. I'm about intermediate level with computing, but I couldn't get smilescombine to work. How do I get Anaconda3 to recoginze the Combiner class? Should I do an import of smilescombine? If so, I couldn't get that to work.

**Comment by LiamWilbraham** [comment]
Hi, thanks for posting this issue and sorry for the delayed response. 

I've improved the installation instructions, which should address this issue. Just pull the changes, `cd` into the `smilescombiine` directory then `pip install -e  .` (or `pip3`).

**Comment by LiamWilbraham** [comment]
I also just uploaded it to pypi, so you should just be able to do `pip install --user smilescombine` now. Thanks!
